FROM node:16

RUN apt -y update \
    && apt -y install software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt -y update \
    && apt -y install python3.10

WORKDIR /opt/app
COPY --from=build /opt/app/venv /venv

ENV PATH="/opt/app/venv/bin:$PATH"
ENV NODE_ENV=container