"""empty message

Revision ID: 24fca93560d0
Revises: 589afea5e010
Create Date: 2023-10-04 03:11:30.967467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fca93560d0'
down_revision = '589afea5e010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pets_id', sa.ARRAY(sa.Integer()), nullable=True))
        batch_op.create_foreign_key(None, 'owner', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pets_id')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
