"""empty message

Revision ID: 8b05da63ce3e
Revises: 70a2ef43be0b
Create Date: 2023-10-18 03:43:11.459724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b05da63ce3e'
down_revision = '70a2ef43be0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keeper_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'keeper', ['keeper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('keeper_id')

    # ### end Alembic commands ###
