"""empty message

Revision ID: 92c6661b2e69
Revises: a741246cc497
Create Date: 2023-10-17 16:21:23.210540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92c6661b2e69'
down_revision = 'a741246cc497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'approved', 'archived', 'canceled', 'done', 'pto', name='status'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
