"""empty message

Revision ID: 9826c02a70cc
Revises: b09205b6f8f4
Create Date: 2023-09-14 16:09:03.628928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9826c02a70cc'
down_revision = 'b09205b6f8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeper', schema=None) as batch_op:
        batch_op.alter_column('services',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.String(length=50)),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeper', schema=None) as batch_op:
        batch_op.alter_column('services',
               existing_type=sa.ARRAY(sa.String(length=50)),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
