"""empty message

Revision ID: b09205b6f8f4
Revises: 0138a40b1c52
Create Date: 2023-09-14 16:04:30.489686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09205b6f8f4'
down_revision = '0138a40b1c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('services', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeper', schema=None) as batch_op:
        batch_op.drop_column('services')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
